name: Code Coverage

on:
  push:
    branches:
      - master
    tags:
      - '!*'
    paths:
      - '.github/workflows/coverage.yaml'
      - '**/*.json'
      - '**/*.py'
      - '**/*.ini'
      - '**/*.toml'
      - '**/*.lock'

jobs:
  coverage:
    name: Run report
    runs-on: ubuntu-latest
    environment: code-cov
    steps:
      - uses: actions/checkout@v4
      - name: Set up test environment
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.x'
          cache: true
      - run: pdm install
      - run: pdm run tox -e coverage
      - uses: paambaati/codeclimate-action@v8
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_REPORTER_ID }}
        with:
          coverageCommand: pdm run coverage lcov
          coverageLocations: ${{github.workspace}}/coverage.lcov:lcov
