name: Regression Testing

on:
  pull_request:
    branches:
      - master
      - release/**
    paths:
      - '.github/workflows/regression.yaml'
      - '**/*.json'
      - '**/*.py'
      - '**/*.ini'
      - '**/*.toml'
      - '**/*.lock'
  push:
    branches:
      - master
      - release/**
    paths:
      - '.github/workflows/regression.yaml'
      - '**/*.json'
      - '**/*.py'
      - '**/*.ini'
      - '**/*.toml'
      - '**/*.lock'

jobs:

  tox-lint:
    name: Basic linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up linting environment
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.x'
          cache: true
      - name: Install dependencies
        run: pdm install
      - name: Lint via standard tox linting environment
        run: pdm run tox -e lint


  tox-matrix:
    name: ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # We want to know what specicic versions it fails on
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest,
        ]
        python-version: [
          '3.10',
          '3.11',
          '3.12',
        #  '3.13',  Some dependencies are not yet compatible with 3.13
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up environment ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
          allow-python-prereleases: true
      - name: Install dependencies
        run: pdm install
      - name: Run regression test suite
        run: |
          pdm run tox -e py${{ matrix.python-version }}
